[theme]
primaryColor="#d33682"
backgroundColor="#002b36"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
font="sans serif"

[server]
port = 8502
enableStaticServing = true

[browser]
gatherUsageStats = false
